version: '3.3'

services:
  be_12455_mysql:
    image: mysql:5
    ports:
      - 12456:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    networks:
      - ksiazker-net
  be_12455_prestashop:
    build:
      dockerfile: .docker/Dockerfile
      context: ./PrestaShop/.
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s
    environment:
      DISABLE_MAKE: 0
      PS_INSTALL_AUTO: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: be_12455_mysql
      DB_PREFIX: ps_
      PS_DOMAIN: localhost:12454
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      PS_COUNTRY: pl
      PS_LANGUAGE: pl
      PS_DEV_MODE: 0
      PS_DEMO_MODE: 0
      PS_HANDLE_DYNAMIC_DOMAIN: 1
      PS_INSTALL_DB: 1
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: ksiazker.obslugaklienta@gmail.com
      ADMIN_PASSWD: ProffesorDziub1ch
    ports:
      - "12454:80"
      - "12455:443"
    networks:
      - ksiazker-net      
networks:
  ksiazker-net:
